[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "awesome-project"
version = "0.1.0"
dependencies = ["numpy>=1.26"]
requires-python = ">= 3.9"